/**
 * Copyright 2016 European Commission
 *
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 *     https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 */
package eu.europa.ec.leos.web.ui.component.documentCard;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DocumentCardDesign extends VerticalLayout {
	protected Label template;
	protected StagePopupView stage;
	protected Label docIcon;
	protected Label title;
	protected Label language;
	protected Label createdBy;
	protected Label createdOn;
	protected Label updatedBy;
	protected Label updatedOn;
	protected Label createdCaption;
	protected Label updatedCaption;

	protected ContributorList contibutorList;
	protected Button addContributorButton;
	protected PropertyBoundButton lockButton;

	protected VerticalLayout actions;
	protected Button openButton;
	protected Button deleteButton;

	public DocumentCardDesign() {
		Design.read(this);
	}
}
