CREATE TABLE LEOS_USER (
USER_LOGIN              VARCHAR2(50 CHAR) PRIMARY KEY,
USER_PER_ID             NUMBER(8) NOT NULL AUTO_INCREMENT,
USER_LASTNAME           VARCHAR2(50 CHAR),
USER_FIRSTNAME          VARCHAR2(50 CHAR),
USER_DG                 VARCHAR2(50),
USER_EMAIL              VARCHAR2(320 CHAR));


CREATE TABLE LEOS_ROLE
   (ROLE_NAME VARCHAR2(50 CHAR) NOT NULL, 
    ROLE_DESC VARCHAR2(50 CHAR),
    CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_NAME)
   );


CREATE TABLE LEOS_USER_ROLE
   (USER_LOGIN VARCHAR2(50  CHAR) NOT NULL, 
    ROLE_NAME VARCHAR2(50 CHAR) NOT NULL
   );


ALTER TABLE LEOS_USER_ROLE ADD CONSTRAINT FK_LOGIN FOREIGN KEY (USER_LOGIN)
     REFERENCES LEOS_USER (USER_LOGIN);


ALTER TABLE LEOS_USER_ROLE ADD CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_NAME)
REFERENCES LEOS_ROLE (ROLE_NAME) ON DELETE CASCADE;

CREATE ALIAS deAccent AS '
  String deAccent(String value) throws Exception{
      return value.toUpperCase();
  }
';
